version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ilhaeng
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ilhaeng"
      MYSQL_USER: "ilhaeng"
      MYSQL_PASSWORD: "ilhaeng7897!"
      TZ: "Asia/Seoul"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-ilhaeng
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch-ilhaeng
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms768m -Xmx768m   # 필요시 512m까지도 가능
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ilhaeng7897!
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 40
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: os-dashboards-ilhaeng
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  opensearch_data: